export interface DashboardResponse {
  success: boolean;
  message: string;
  data: {
    dashboard: {
      kpis: {
        title: string;
        value: number;
        change: number;
        changeType: "increase" | "decrease";
        icon: string;
        color: string;
        format: string;
      }[];
      salesData: {
        labels: string[];
        sales: number[];
        revenue: number[];
        orders: number[];
      };
      revenueBreakdown: unknown[];
      recentOrders: unknown[];
      topBooks: unknown[];
      notifications: unknown[];
      recentCustomers: {
        id: string;
        name: string;
        email: string;
        avatar: string;
        joinDate: string;
        totalOrders: number;
        totalSpent: number;
        status: string;
      }[];
    };
    metadata: {
      lastUpdated: string;
      timezone: string;
      currency: string;
      currencySymbol: string;
    };
  };
}

export interface DashboardOrder {
  id: string;
  orderNumber: string;
  items: number;
  customerName: string;
  customerEmail: string;
  amount: number;
  status: string;
  date: string;
}

export interface DashboardNotification {
  id: string;
  type: string;
  priority: string;
  title: string;
  message: string;
  time: string;
  read: boolean;
}

export interface DashboardProduct {
  id: string;
  name: string;
  category: string;
  rating: number;
  sales: number;
  revenue: number;
  stock: number;
}

// Affiliate Dashboard Types

export interface AffiliateDashboardResponse {
  success: boolean;
  message: string;
  data: AffiliateDashboardData;
}

export interface AffiliateDashboardData {
  kpiCards: AffiliateKPICards;
  affiliateSettings: AffiliateSettings;
  leaderboard: AffiliateLeaderboardEntry[];
  overview: AffiliateOverview;
  payouts: AffiliatePayout[];
  events: AffiliateEvent[];
  analytics: AffiliateAnalytics;
}

export interface AffiliateKPICards {
  totalRevenue: number;         // Total revenue generated (₦)
  totalAffiliates: number;      // Total number of affiliates
  totalClicks: number;          // Total number of referral link clicks
  totalConversions: number;     // Total number of successful conversions
  pendingPayouts: number;       // Total pending payouts to affiliates (₦)
}

export interface AffiliateSettings {
  affiliatePercentage: number;  // Commission percentage for affiliates
  minimumAffiliates: number;   // Minimum affiliates required to qualify for rewards
  rewardThreshold: number;     // Minimum amount (₦) before payout is allowed
  expirationDays: number;      // Days before referral link expires
}

export interface AffiliateLeaderboardEntry {
  id: string;                  // Unique affiliate ID
  name: string;                // Affiliate's name
  email: string;               // Affiliate's email
  revenue: number;             // Revenue generated by this affiliate (₦)
  clicks: number;              // Number of clicks generated
  conversions: number;         // Number of conversions
  status: string;              // Affiliate status (active/pending/inactive)
  joinedAt: string;            // Date affiliate joined (ISO 8601)
}

export interface AffiliateOverview {
  timeframes: string[];        // Available timeframes
  selectedTimeframe: string;   // Currently selected timeframe
  summary: AffiliateOverviewSummary;
  trendData: AffiliateOverviewTrend[];
}

export interface AffiliateOverviewSummary {
  revenue: number;             // Revenue in selected timeframe (₦)
  clicks: number;              // Clicks in selected timeframe
  conversions: number;         // Conversions in selected timeframe
  newAffiliates: number;       // New affiliates in selected timeframe
}

export interface AffiliateOverviewTrend {
  date: string;                // Date (YYYY-MM-DD)
  revenue: number;             // Revenue for the day (₦)
  clicks: number;              // Clicks for the day
  conversions: number;         // Conversions for the day
}

export interface AffiliatePayout {
  payoutId: string;            // Unique payout ID
  affiliateId: string;         // Affiliate ID
  affiliateName: string;       // Affiliate's name
  amount: number;              // Payout amount (₦)
  status: string;              // Payout status (pending/completed)
  requestedAt: string;         // Date payout was requested (ISO 8601)
  paidAt: string | null;       // Date payout was completed (null if pending)
  accountDetails: {
    bankName: string;
    accountNumber: string;
    accountName: string;
    bankCode: string;
  } | null;                    // Bank account details for payout
  payoutMethod: string | null; // Payout method (e.g., "bank transfer")
  withdrawalStatus: string | null; // Withdrawal status
}

export interface AffiliateEvent {
  eventId: string;             // Unique event ID
  type: string;                // Event type (conversion, payout_requested, etc.)
  affiliateId: string;         // Affiliate ID
  affiliateName: string;       // Affiliate's name
  timestamp: string;           // Event timestamp (ISO 8601)
  details: string;             // Event details/description
}

export interface AffiliateAnalytics {
  conversionRate: number;      // Overall conversion rate (%)
  averageOrderValue: number;   // Average order value (₦)
  topSources: AffiliateAnalyticsSource[];
  geoDistribution: AffiliateAnalyticsGeo[];
}

export interface AffiliateAnalyticsSource {
  source: string;              // Traffic source (e.g., Facebook)
  clicks: number;              // Number of clicks from this source
  conversions: number;         // Number of conversions from this source
}

export interface AffiliateAnalyticsGeo {
  country: string;             // Country name
  clicks: number;              // Number of clicks from this country
  conversions: number;         // Number of conversions from this country
}